### ISSUE TITLE
Domain names for technical uses

### ISSUE THREAD

**Issue by paulehoffman** [DNSOP/draft-ietf-dnsop-terminology-bis#14]
Bob Harold requests:

Under Global DNS -> Administration of names, add "Domain Names for technical uses are administered by IETF"

**Comment by paulehoffman** [comment]
Given the recent IAB statement that special use domain names do not go in the root but instead into a zone administered by the IAB (such as .arpa), I think this suggestion is incorrect.

**Comment by suzworldwide** [comment]
Hi,

A little precision will be helpful here.

The IAB statement was about a fairly specific subset of special use names: those intended for resolution in the DNS and defined in IETF standards.

About such names, the IAB said "In the view of the IAB, when placing any name in the Special-Use Domain Names registry with the intention that it be used with the DNS protocol, such an entry must be within a domain under the control of the body making the registration. For the IETF, an appropriate domain for such names would be ARPA, as long as those names meet the conditions in RFC 3172.”

This doesn’t apply to names defined outside of the IETF standards process because RFC 3172 specifies IETF standards action as one of the conditions for adding names to .arpa. The IAB might have opinions about other DNS names too, but there’s no way for the IETF to direct the IAB to approve adding them to .arpa. (It might be interesting to try with a reservation under RFC 6761 that’s intended to resolve with DNS but doesn’t have an IETF standard behind it. However, we haven’t done such a thing and I don’t know what would happen— that case isn’t covered by RFC 3172.)

It also doesn’t apply to names not intended to resolve in the DNS, because there’s no obvious necessity in such cases (so far) for the registrant to control the DNS name. Again, if such a case could be made, the delegation of the name under .arpa might well be appropriate, and by my reading of RFC 3172, would be permitted if it were part of an IETF standard….but it’s not something we’ve done, and it’s not what the IAB statement addresses.


Suzanne

**Comment by paulehoffman** [comment]
> The IAB statement was about a fairly specific subset of special use names: those intended for resolution in the DNS and defined in IETF standards.

Exactly right. This issue is about changing a section under "Global DNS".
