### ISSUE TITLE
Add "validating resolver" to DNSSEC section

### ISSUE THREAD

**Issue by danyork** [DNSOP/draft-ietf-dnsop-terminology-bis#18]
In the current section "8. General DNSSEC", it may be helpful to define:

----

Validating resolver: A recursive or stub resolver that performs DNSSEC validation. Sometimes also called a "DNSSEC-validating resolver".

----

I mention this in part because section "9. DNSSEC States" begins with the text " _A **validating resolver** can determine that a response is in one of four states: secure, insecure, bogus, or indeterminate._ "

**Comment by paulehoffman** [comment]
Yes, it's not defined currently. We even say that in the document. I'm a bit hesitant to give it a definition because it is not clear whether "performs DNSSEC validation" is sufficient. I think that it has to perform validation and change the responses if validation fails, and those responses are different if it is a stub or recursive.

**Comment by crankycanuck** [comment]
Will add some suggested text.

**Comment by paulehoffman** [comment]
@crankycanuck: awaiting that text.
